#!/bin/bash
# Export script for restaurant-daily environment variables

echo "# Restaurant Daily Environment Export"
echo "# Run this on target machine: source export-env.sh"
echo ""
echo "# Vault Configuration"
echo "export VAULT_ADDR='http://127.0.0.1:8200'"
echo "export VAULT_TOKEN='[GET_FROM_VAULT_SERVER_OUTPUT]'"
echo ""
echo "# Project Configuration"
echo "export SUPABASE_URL='https://hukaqbgfmerutzhtchiu.supabase.co'"
echo ""
echo "# Fallback secrets (development only)"
echo "export JWT_SECRET='your-super-secret-jwt-key-for-development'"
echo "export SUPABASE_SERVICE_ROLE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1a2FxYmdmbWVydXR6aHRjaGl1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczNzU1MDcyOSwiZXhwIjoyMDUzMTI2NzI5fQ.L7e3OvFKJxh-Ej_Ao8xJUjkm1C5T5ZVqVuRJxbBGUEA'"
echo "export NEXT_PUBLIC_SUPABASE_ANON_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1a2FxYmdmbWVydXR6aHRjaGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTA3MjksImV4cCI6MjA1MzEyNjcyOX0.kGX7V8Z7kuIjmQNHp0hCwx4kQ01u15X0WlW6EW5cM28'"
echo ""
echo ""
echo "echo '🔧 SETUP INSTRUCTIONS:'"
echo "echo '1. Replace [GET_FROM_VAULT_SERVER_OUTPUT] with actual Vault token'"
echo "echo '2. Start Vault server: vault server -dev'"
echo "echo '3. Copy the Root Token from server output'"
echo "echo '4. Run: source export-env.sh'"
echo "echo ''"
echo "echo 'Environment variables exported for restaurant-daily'"
echo "echo 'Vault status:'"
echo "vault status 2>/dev/null || echo 'Vault not accessible - using fallback secrets'"